model:
  heads:
    object:
      type: CenterHead
      in_channels: null
      train_cfg:
        point_cloud_range: ${point_cloud_range}
        grid_size: [2000, 2000, 1]
        voxel_size: ${voxel_size}
        out_size_factor: 8
        dense_reg: 1
        gaussian_overlap: 0.1
        max_objs: 500
        min_radius: 2
        code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
      test_cfg:
        post_center_limit_range: [-85.0, -85.0, -10.0, 85.0, 85.0, 10.0]
        max_per_img: 500
        max_pool_nms: false
        min_radius: [4, 12, 10, 1, 0.85, 0.175]
        score_threshold: 0.1
        out_size_factor: 8
        voxel_size: ${voxel_size[:2]}
        nms_type: rotate
        pre_max_size: 1000
        post_max_size: 83
        nms_thr: 0.075
      tasks:
        - ["CAR"]
        - ["VAN"]
        - ["TRUCK", "OTHER"]
        - ["BUS", "TRAILER"]
        - ["PEDESTRIAN"]
        - ["BICYCLE", "MOTORCYCLE"]
        #- ["CAR"]
        #- ["TRUCK", "VAN"]
        #- ["BUS", "TRAILER"]
        #- ["PEDESTRIAN", "OTHER"]
        #- ["BICYCLE", "MOTORCYCLE"]
        #- ["EMERGENCY_VEHICLE"]
      common_heads:
        reg: [2, 2]
        height: [1, 2]
        dim: [3, 2]
        rot: [2, 2]
        vel: [2, 2]
      share_conv_channel: 64
      bbox_coder:
        type: CenterPointBBoxCoder
        pc_range: ${point_cloud_range}
        post_center_range: [-85.0, -85.0, -10.0, 85.0, 85.0, 10.0]
        max_num: 500
        score_threshold: 0.1
        out_size_factor: 8
        voxel_size: ${voxel_size[:2]}
        code_size: 9
      separate_head:
        type: SeparateHead
        init_bias: -2.19
        final_kernel: 3
      loss_cls:
        type: GaussianFocalLoss
        reduction: mean
      loss_bbox:
        type: L1Loss
        reduction: mean
        loss_weight: 0.25
      norm_bbox: true
